-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Schema.Blog.Object.Article exposing (..)

import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode
import Schema.Blog.InputObject
import Schema.Blog.Interface
import Schema.Blog.Object
import Schema.Blog.Scalar
import Schema.Blog.ScalarCodecs
import Schema.Blog.Union


{-| -}
uid : SelectionSet String Schema.Blog.Object.Article
uid =
    Object.selectionForField "String" "uid" [] Decode.string


{-| -}
title : SelectionSet String Schema.Blog.Object.Article
title =
    Object.selectionForField "String" "title" [] Decode.string


{-| -}
markdown : SelectionSet String Schema.Blog.Object.Article
markdown =
    Object.selectionForField "String" "markdown" [] Decode.string


{-| -}
html : SelectionSet String Schema.Blog.Object.Article
html =
    Object.selectionForField "String" "html" [] Decode.string


{-| -}
draft : SelectionSet Bool Schema.Blog.Object.Article
draft =
    Object.selectionForField "Bool" "draft" [] Decode.bool


{-| -}
created_at : SelectionSet Int Schema.Blog.Object.Article
created_at =
    Object.selectionForField "Int" "created_at" [] Decode.int


{-| -}
modified_at : SelectionSet Int Schema.Blog.Object.Article
modified_at =
    Object.selectionForField "Int" "modified_at" [] Decode.int


{-| -}
prev :
    SelectionSet decodesTo Schema.Blog.Object.Article
    -> SelectionSet (Maybe decodesTo) Schema.Blog.Object.Article
prev object_ =
    Object.selectionForCompositeField "prev" [] object_ (identity >> Decode.nullable)


{-| -}
next :
    SelectionSet decodesTo Schema.Blog.Object.Article
    -> SelectionSet (Maybe decodesTo) Schema.Blog.Object.Article
next object_ =
    Object.selectionForCompositeField "next" [] object_ (identity >> Decode.nullable)
