-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Schema.Blog.Query exposing (..)

import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode exposing (Decoder)
import Schema.Blog.InputObject
import Schema.Blog.Interface
import Schema.Blog.Object
import Schema.Blog.Scalar
import Schema.Blog.ScalarCodecs
import Schema.Blog.Union


{-| -}
publicArticles :
    SelectionSet decodesTo Schema.Blog.Object.Article
    -> SelectionSet (List decodesTo) RootQuery
publicArticles object_ =
    Object.selectionForCompositeField "publicArticles" [] object_ (identity >> Decode.list)


{-| -}
draftArticles :
    SelectionSet decodesTo Schema.Blog.Object.Article
    -> SelectionSet (List decodesTo) RootQuery
draftArticles object_ =
    Object.selectionForCompositeField "draftArticles" [] object_ (identity >> Decode.list)


type alias ArticleRequiredArguments =
    { uid : String }


{-|

  - uid -

-}
article :
    ArticleRequiredArguments
    -> SelectionSet decodesTo Schema.Blog.Object.Article
    -> SelectionSet (Maybe decodesTo) RootQuery
article requiredArgs object_ =
    Object.selectionForCompositeField "article" [ Argument.required "uid" requiredArgs.uid Encode.string ] object_ (identity >> Decode.nullable)


{-| -}
latestArticle :
    SelectionSet decodesTo Schema.Blog.Object.Article
    -> SelectionSet (Maybe decodesTo) RootQuery
latestArticle object_ =
    Object.selectionForCompositeField "latestArticle" [] object_ (identity >> Decode.nullable)
